name: GahvilaCore
version: '${version}'
main: net.gahvila.gahvilacore.GahvilaCore
authors: [Jokni, M1xed]
api-version: '1.21'
load: STARTUP
dependencies:
  server:
    WorldGuard:
      required: false
    LuckPerms:
      required: true
    PlaceholderAPI:
      required: true
    CarbonChat:
      required: false