name: GahvilaCore
version: '2.0'
main: net.gahvila.gahvilacore.GahvilaCore
authors: [Jokni, M1xed]
api-version: '1.20'
dependencies:
  server:
    LuckPerms:
      required: true
    PlaceholderAPI:
      required: true
    CarbonChat:
      required: true

